package cn.ac.sec.entity;

import java.util.Date;

public class BizDataWatchKey {
    private Long userId;
    private String tableName;

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data_watch_BP.datetime_measure
     *
     * @mbggenerated
     */
    private Date datetimeMeasure;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data_watch_BP
     *
     * @mbggenerated
     */
    public BizDataWatchKey(Long userId, Date datetimeMeasure) {
        this.userId = userId;
        this.datetimeMeasure = datetimeMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data_watch_BP
     *
     * @mbggenerated
     */
    public BizDataWatchKey() {
        super();
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data_watch_BP.IMEI_
     *
     * @return the value of biz_data_watch_BP.IMEI_
     *
     * @mbggenerated
     */



    public Date getDatetimeMeasure() {
        return datetimeMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data_watch_BP.datetime_measure
     *
     * @param datetimeMeasure the value for biz_data_watch_BP.datetime_measure
     *
     * @mbggenerated
     */
    public void setDatetimeMeasure(Date datetimeMeasure) {
        this.datetimeMeasure = datetimeMeasure;
    }
}
