package cn.ac.sec.entity;

import java.io.Serializable;

public class BizMessageAlarmType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.id_
     *
     * @mbggenerated
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.icon_
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.level_
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.order_
     *
     * @mbggenerated
     */
    private Byte order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.code_
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.device_type
     *
     * @mbggenerated
     */
    private Byte deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_alarm_type.description_
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    public BizMessageAlarmType(Byte id, String name, String icon, Byte level, Byte order, String code, Byte deviceType, String description) {
        this.id = id;
        this.name = name;
        this.icon = icon;
        this.level = level;
        this.order = order;
        this.code = code;
        this.deviceType = deviceType;
        this.description = description;
    }

    public BizMessageAlarmType(Byte id,String name,String icon,Byte level,Byte order,String code,Byte deviceType){
        this.id = id;
        this.name = name;
        this.icon = icon;
        this.level = level;
        this.order = order;
        this.code = code;
        this.deviceType = deviceType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    public BizMessageAlarmType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.id_
     *
     * @return the value of biz_message_alarm_type.id_
     *
     * @mbggenerated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.id_
     *
     * @param id the value for biz_message_alarm_type.id_
     *
     * @mbggenerated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.name_
     *
     * @return the value of biz_message_alarm_type.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.name_
     *
     * @param name the value for biz_message_alarm_type.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.icon_
     *
     * @return the value of biz_message_alarm_type.icon_
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.icon_
     *
     * @param icon the value for biz_message_alarm_type.icon_
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.level_
     *
     * @return the value of biz_message_alarm_type.level_
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.level_
     *
     * @param level the value for biz_message_alarm_type.level_
     *
     * @mbggenerated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.order_
     *
     * @return the value of biz_message_alarm_type.order_
     *
     * @mbggenerated
     */
    public Byte getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.order_
     *
     * @param order the value for biz_message_alarm_type.order_
     *
     * @mbggenerated
     */
    public void setOrder(Byte order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.code_
     *
     * @return the value of biz_message_alarm_type.code_
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.code_
     *
     * @param code the value for biz_message_alarm_type.code_
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.device_type
     *
     * @return the value of biz_message_alarm_type.device_type
     *
     * @mbggenerated
     */
    public Byte getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.device_type
     *
     * @param deviceType the value for biz_message_alarm_type.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(Byte deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_alarm_type.description_
     *
     * @return the value of biz_message_alarm_type.description_
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_alarm_type.description_
     *
     * @param description the value for biz_message_alarm_type.description_
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}