package cn.ac.sec.entity;

import java.io.Serializable;
import java.util.Date;

public class BizMessagePosition implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_position.id_
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_position.user_
     *
     * @mbggenerated
     */
    private Long user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_position.time_
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_position.timestamp_
     *
     * @mbggenerated
     */
    private Integer timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_position.longitude_
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_message_position.latitude_
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    public BizMessagePosition(Long id, Long user, Date time, Integer timestamp, Double longitude, Double latitude) {
        this.id = id;
        this.user = user;
        this.time = time;
        this.timestamp = timestamp;
        this.longitude = longitude;
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    public BizMessagePosition() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_position.id_
     *
     * @return the value of biz_message_position.id_
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_position.id_
     *
     * @param id the value for biz_message_position.id_
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_position.user_
     *
     * @return the value of biz_message_position.user_
     *
     * @mbggenerated
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_position.user_
     *
     * @param user the value for biz_message_position.user_
     *
     * @mbggenerated
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_position.time_
     *
     * @return the value of biz_message_position.time_
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_position.time_
     *
     * @param time the value for biz_message_position.time_
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_position.timestamp_
     *
     * @return the value of biz_message_position.timestamp_
     *
     * @mbggenerated
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_position.timestamp_
     *
     * @param timestamp the value for biz_message_position.timestamp_
     *
     * @mbggenerated
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_position.longitude_
     *
     * @return the value of biz_message_position.longitude_
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_position.longitude_
     *
     * @param longitude the value for biz_message_position.longitude_
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_message_position.latitude_
     *
     * @return the value of biz_message_position.latitude_
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_message_position.latitude_
     *
     * @param latitude the value for biz_message_position.latitude_
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}