package cn.ac.sec.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BizRelationUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public BizRelationUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIsNull() {
            addCriterion("parent_ is null");
            return (Criteria) this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("parent_ is not null");
            return (Criteria) this;
        }

        public Criteria andParentEqualTo(Long value) {
            addCriterion("parent_ =", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotEqualTo(Long value) {
            addCriterion("parent_ <>", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThan(Long value) {
            addCriterion("parent_ >", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_ >=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThan(Long value) {
            addCriterion("parent_ <", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThanOrEqualTo(Long value) {
            addCriterion("parent_ <=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentIn(List<Long> values) {
            addCriterion("parent_ in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotIn(List<Long> values) {
            addCriterion("parent_ not in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentBetween(Long value1, Long value2) {
            addCriterion("parent_ between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotBetween(Long value1, Long value2) {
            addCriterion("parent_ not between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andChildIsNull() {
            addCriterion("child_ is null");
            return (Criteria) this;
        }

        public Criteria andChildIsNotNull() {
            addCriterion("child_ is not null");
            return (Criteria) this;
        }

        public Criteria andChildEqualTo(Long value) {
            addCriterion("child_ =", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildNotEqualTo(Long value) {
            addCriterion("child_ <>", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildGreaterThan(Long value) {
            addCriterion("child_ >", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildGreaterThanOrEqualTo(Long value) {
            addCriterion("child_ >=", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildLessThan(Long value) {
            addCriterion("child_ <", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildLessThanOrEqualTo(Long value) {
            addCriterion("child_ <=", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildIn(List<Long> values) {
            addCriterion("child_ in", values, "child");
            return (Criteria) this;
        }

        public Criteria andChildNotIn(List<Long> values) {
            addCriterion("child_ not in", values, "child");
            return (Criteria) this;
        }

        public Criteria andChildBetween(Long value1, Long value2) {
            addCriterion("child_ between", value1, value2, "child");
            return (Criteria) this;
        }

        public Criteria andChildNotBetween(Long value1, Long value2) {
            addCriterion("child_ not between", value1, value2, "child");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNull() {
            addCriterion("add_date is null");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNotNull() {
            addCriterion("add_date is not null");
            return (Criteria) this;
        }

        public Criteria andAddDateEqualTo(Date value) {
            addCriterion("add_date =", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotEqualTo(Date value) {
            addCriterion("add_date <>", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThan(Date value) {
            addCriterion("add_date >", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThanOrEqualTo(Date value) {
            addCriterion("add_date >=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThan(Date value) {
            addCriterion("add_date <", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThanOrEqualTo(Date value) {
            addCriterion("add_date <=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateIn(List<Date> values) {
            addCriterion("add_date in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotIn(List<Date> values) {
            addCriterion("add_date not in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateBetween(Date value1, Date value2) {
            addCriterion("add_date between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotBetween(Date value1, Date value2) {
            addCriterion("add_date not between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusIsNull() {
            addCriterion("unbind_status is null");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusIsNotNull() {
            addCriterion("unbind_status is not null");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusEqualTo(Byte value) {
            addCriterion("unbind_status =", value, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusNotEqualTo(Byte value) {
            addCriterion("unbind_status <>", value, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusGreaterThan(Byte value) {
            addCriterion("unbind_status >", value, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("unbind_status >=", value, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusLessThan(Byte value) {
            addCriterion("unbind_status <", value, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusLessThanOrEqualTo(Byte value) {
            addCriterion("unbind_status <=", value, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusIn(List<Byte> values) {
            addCriterion("unbind_status in", values, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusNotIn(List<Byte> values) {
            addCriterion("unbind_status not in", values, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusBetween(Byte value1, Byte value2) {
            addCriterion("unbind_status between", value1, value2, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("unbind_status not between", value1, value2, "unbindStatus");
            return (Criteria) this;
        }

        public Criteria andUnbindDateIsNull() {
            addCriterion("unbind_date is null");
            return (Criteria) this;
        }

        public Criteria andUnbindDateIsNotNull() {
            addCriterion("unbind_date is not null");
            return (Criteria) this;
        }

        public Criteria andUnbindDateEqualTo(Date value) {
            addCriterion("unbind_date =", value, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateNotEqualTo(Date value) {
            addCriterion("unbind_date <>", value, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateGreaterThan(Date value) {
            addCriterion("unbind_date >", value, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateGreaterThanOrEqualTo(Date value) {
            addCriterion("unbind_date >=", value, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateLessThan(Date value) {
            addCriterion("unbind_date <", value, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateLessThanOrEqualTo(Date value) {
            addCriterion("unbind_date <=", value, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateIn(List<Date> values) {
            addCriterion("unbind_date in", values, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateNotIn(List<Date> values) {
            addCriterion("unbind_date not in", values, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateBetween(Date value1, Date value2) {
            addCriterion("unbind_date between", value1, value2, "unbindDate");
            return (Criteria) this;
        }

        public Criteria andUnbindDateNotBetween(Date value1, Date value2) {
            addCriterion("unbind_date not between", value1, value2, "unbindDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_relation_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}