package cn.ac.sec.entity;

import java.io.Serializable;
import java.util.Date;

public class BizRelationTagUser implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.id_
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.tag_
     *
     * @mbggenerated
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.user_
     *
     * @mbggenerated
     */
    private Long user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.add_user
     *
     * @mbggenerated
     */
    private Long addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_tag_user
     *
     * @mbggenerated
     */
    public BizRelationTagUser(Long id, Integer tag, Long user, Long addUser, Date addTime) {
        this.id = id;
        this.tag = tag;
        this.user = user;
        this.addUser = addUser;
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_tag_user
     *
     * @mbggenerated
     */
    public BizRelationTagUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.id_
     *
     * @return the value of biz_relation_tag_user.id_
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.id_
     *
     * @param id the value for biz_relation_tag_user.id_
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.tag_
     *
     * @return the value of biz_relation_tag_user.tag_
     *
     * @mbggenerated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.tag_
     *
     * @param tag the value for biz_relation_tag_user.tag_
     *
     * @mbggenerated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.user_
     *
     * @return the value of biz_relation_tag_user.user_
     *
     * @mbggenerated
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.user_
     *
     * @param user the value for biz_relation_tag_user.user_
     *
     * @mbggenerated
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.add_user
     *
     * @return the value of biz_relation_tag_user.add_user
     *
     * @mbggenerated
     */
    public Long getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.add_user
     *
     * @param addUser the value for biz_relation_tag_user.add_user
     *
     * @mbggenerated
     */
    public void setAddUser(Long addUser) {
        this.addUser = addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.add_time
     *
     * @return the value of biz_relation_tag_user.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.add_time
     *
     * @param addTime the value for biz_relation_tag_user.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}