package cn.ac.sec.entity;

import java.io.Serializable;

public class BizRelationUserKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_user.parent_
     *
     * @mbggenerated
     */
    private Long parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_user.child_
     *
     * @mbggenerated
     */
    private Long child;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public BizRelationUserKey(Long parent, Long child) {
        this.parent = parent;
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    public BizRelationUserKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_user.parent_
     *
     * @return the value of biz_relation_user.parent_
     *
     * @mbggenerated
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_user.parent_
     *
     * @param parent the value for biz_relation_user.parent_
     *
     * @mbggenerated
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_user.child_
     *
     * @return the value of biz_relation_user.child_
     *
     * @mbggenerated
     */
    public Long getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_user.child_
     *
     * @param child the value for biz_relation_user.child_
     *
     * @mbggenerated
     */
    public void setChild(Long child) {
        this.child = child;
    }
}