package cn.ac.sec.entity;

import java.io.Serializable;

public class BizRelationTagUserKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.tag_
     *
     * @mbggenerated
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_relation_tag_user.user_
     *
     * @mbggenerated
     */
    private Long user;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_tag_user
     *
     * @mbggenerated
     */
    public BizRelationTagUserKey(Integer tag, Long user) {
        this.tag = tag;
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_tag_user
     *
     * @mbggenerated
     */
    public BizRelationTagUserKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.tag_
     *
     * @return the value of biz_relation_tag_user.tag_
     *
     * @mbggenerated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.tag_
     *
     * @param tag the value for biz_relation_tag_user.tag_
     *
     * @mbggenerated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_relation_tag_user.user_
     *
     * @return the value of biz_relation_tag_user.user_
     *
     * @mbggenerated
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_relation_tag_user.user_
     *
     * @param user the value for biz_relation_tag_user.user_
     *
     * @mbggenerated
     */
    public void setUser(Long user) {
        this.user = user;
    }
}