package cn.ac.sec.entity;

import java.io.Serializable;
import java.util.Date;

public class BizUserComplain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.id_
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.complain_content
     *
     * @mbggenerated
     */
    private String complainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.complain_user
     *
     * @mbggenerated
     */
    private Long complainUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.complain_date
     *
     * @mbggenerated
     */
    private Date complainDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.process_user
     *
     * @mbggenerated
     */
    private Long processUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.process_date
     *
     * @mbggenerated
     */
    private Date processDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.process_content
     *
     * @mbggenerated
     */
    private String processContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_complain.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_complain
     *
     * @mbggenerated
     */
    public BizUserComplain(Long id, String complainContent, Long complainUser, Date complainDate, Long processUser, Date processDate, String processContent, String phoneNum) {
        this.id = id;
        this.complainContent = complainContent;
        this.complainUser = complainUser;
        this.complainDate = complainDate;
        this.processUser = processUser;
        this.processDate = processDate;
        this.processContent = processContent;
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_complain
     *
     * @mbggenerated
     */
    public BizUserComplain() {
        super ();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.id_
     *
     * @return the value of biz_user_complain.id_
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.id_
     *
     * @param id the value for biz_user_complain.id_
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.complain_content
     *
     * @return the value of biz_user_complain.complain_content
     * @mbggenerated
     */
    public String getComplainContent() {
        return complainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.complain_content
     *
     * @param complainContent the value for biz_user_complain.complain_content
     * @mbggenerated
     */
    public void setComplainContent(String complainContent) {
        this.complainContent = complainContent == null ? null : complainContent.trim ();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.complain_user
     *
     * @return the value of biz_user_complain.complain_user
     * @mbggenerated
     */
    public Long getComplainUser() {
        return complainUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.complain_user
     *
     * @param complainUser the value for biz_user_complain.complain_user
     * @mbggenerated
     */
    public void setComplainUser(Long complainUser) {
        this.complainUser = complainUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.complain_date
     *
     * @return the value of biz_user_complain.complain_date
     * @mbggenerated
     */
    public Date getComplainDate() {
        return complainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.complain_date
     *
     * @param complainDate the value for biz_user_complain.complain_date
     * @mbggenerated
     */
    public void setComplainDate(Date complainDate) {
        this.complainDate = complainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.process_user
     *
     * @return the value of biz_user_complain.process_user
     * @mbggenerated
     */
    public Long getProcessUser() {
        return processUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.process_user
     *
     * @param processUser the value for biz_user_complain.process_user
     * @mbggenerated
     */
    public void setProcessUser(Long processUser) {
        this.processUser = processUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.process_date
     *
     * @return the value of biz_user_complain.process_date
     * @mbggenerated
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.process_date
     *
     * @param processDate the value for biz_user_complain.process_date
     * @mbggenerated
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.process_content
     *
     * @return the value of biz_user_complain.process_content
     * @mbggenerated
     */
    public String getProcessContent() {
        return processContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.process_content
     *
     * @param processContent the value for biz_user_complain.process_content
     * @mbggenerated
     */
    public void setProcessContent(String processContent) {
        this.processContent = processContent == null ? null : processContent.trim ();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_complain.phone_num
     *
     * @return the value of biz_user_complain.phone_num
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_complain.phone_num
     *
     * @param phoneNum the value for biz_user_complain.phone_num
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim ();
    }
}