package cn.ac.sec.entity;

import java.io.Serializable;
import java.util.Date;

public class BizUserSubscription implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_subscription.id_
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_subscription.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_subscription.created_by
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_subscription.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_subscription.time_limit
     *
     * @mbggenerated
     */
    private Integer timeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user_subscription.expiration_time
     *
     * @mbggenerated
     */
    private Date expirationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_subscription
     *
     * @mbggenerated
     */
    public BizUserSubscription(Long id, Long userId, Long createdBy, Date createdDate, Integer timeLimit, Date expirationTime) {
        this.id = id;
        this.userId = userId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.timeLimit = timeLimit;
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_subscription
     *
     * @mbggenerated
     */
    public BizUserSubscription() {
        super ();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_subscription.id_
     *
     * @return the value of biz_user_subscription.id_
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_subscription.id_
     *
     * @param id the value for biz_user_subscription.id_
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_subscription.user_id
     *
     * @return the value of biz_user_subscription.user_id
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_subscription.user_id
     *
     * @param userId the value for biz_user_subscription.user_id
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_subscription.created_by
     *
     * @return the value of biz_user_subscription.created_by
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_subscription.created_by
     *
     * @param createdBy the value for biz_user_subscription.created_by
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_subscription.created_date
     *
     * @return the value of biz_user_subscription.created_date
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_subscription.created_date
     *
     * @param createdDate the value for biz_user_subscription.created_date
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_subscription.time_limit
     *
     * @return the value of biz_user_subscription.time_limit
     * @mbggenerated
     */
    public Integer getTimeLimit() {
        return timeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_subscription.time_limit
     *
     * @param timeLimit the value for biz_user_subscription.time_limit
     * @mbggenerated
     */
    public void setTimeLimit(Integer timeLimit) {
        this.timeLimit = timeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user_subscription.expiration_time
     *
     * @return the value of biz_user_subscription.expiration_time
     * @mbggenerated
     */
    public Date getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user_subscription.expiration_time
     *
     * @param expirationTime the value for biz_user_subscription.expiration_time
     * @mbggenerated
     */
    public void setExpirationTime(Date expirationTime) {
        this.expirationTime = expirationTime;
    }
}