package cn.ac.sec.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BizWatchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public BizWatchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("IMEI_ is null");
            return (Criteria) this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("IMEI_ is not null");
            return (Criteria) this;
        }

        public Criteria andImeiEqualTo(Long value) {
            addCriterion("IMEI_ =", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotEqualTo(Long value) {
            addCriterion("IMEI_ <>", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThan(Long value) {
            addCriterion("IMEI_ >", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(Long value) {
            addCriterion("IMEI_ >=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThan(Long value) {
            addCriterion("IMEI_ <", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThanOrEqualTo(Long value) {
            addCriterion("IMEI_ <=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiIn(List<Long> values) {
            addCriterion("IMEI_ in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotIn(List<Long> values) {
            addCriterion("IMEI_ not in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiBetween(Long value1, Long value2) {
            addCriterion("IMEI_ between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotBetween(Long value1, Long value2) {
            addCriterion("IMEI_ not between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeIsNull() {
            addCriterion("last_online_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeIsNotNull() {
            addCriterion("last_online_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeEqualTo(Date value) {
            addCriterion("last_online_time =", value, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeNotEqualTo(Date value) {
            addCriterion("last_online_time <>", value, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeGreaterThan(Date value) {
            addCriterion("last_online_time >", value, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_online_time >=", value, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeLessThan(Date value) {
            addCriterion("last_online_time <", value, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_online_time <=", value, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeIn(List<Date> values) {
            addCriterion("last_online_time in", values, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeNotIn(List<Date> values) {
            addCriterion("last_online_time not in", values, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeBetween(Date value1, Date value2) {
            addCriterion("last_online_time between", value1, value2, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andLastOnlineTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_online_time not between", value1, value2, "lastOnlineTime");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumIsNull() {
            addCriterion("watch_phone_num is null");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumIsNotNull() {
            addCriterion("watch_phone_num is not null");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumEqualTo(String value) {
            addCriterion("watch_phone_num =", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumNotEqualTo(String value) {
            addCriterion("watch_phone_num <>", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumGreaterThan(String value) {
            addCriterion("watch_phone_num >", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumGreaterThanOrEqualTo(String value) {
            addCriterion("watch_phone_num >=", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumLessThan(String value) {
            addCriterion("watch_phone_num <", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumLessThanOrEqualTo(String value) {
            addCriterion("watch_phone_num <=", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumLike(String value) {
            addCriterion("watch_phone_num like", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumNotLike(String value) {
            addCriterion("watch_phone_num not like", value, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumIn(List<String> values) {
            addCriterion("watch_phone_num in", values, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumNotIn(List<String> values) {
            addCriterion("watch_phone_num not in", values, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumBetween(String value1, String value2) {
            addCriterion("watch_phone_num between", value1, value2, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andWatchPhoneNumNotBetween(String value1, String value2) {
            addCriterion("watch_phone_num not between", value1, value2, "watchPhoneNum");
            return (Criteria) this;
        }

        public Criteria andUserIsNull() {
            addCriterion("user_ is null");
            return (Criteria) this;
        }

        public Criteria andUserIsNotNull() {
            addCriterion("user_ is not null");
            return (Criteria) this;
        }

        public Criteria andUserEqualTo(Long value) {
            addCriterion("user_ =", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotEqualTo(Long value) {
            addCriterion("user_ <>", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThan(Long value) {
            addCriterion("user_ >", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThanOrEqualTo(Long value) {
            addCriterion("user_ >=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThan(Long value) {
            addCriterion("user_ <", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThanOrEqualTo(Long value) {
            addCriterion("user_ <=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserIn(List<Long> values) {
            addCriterion("user_ in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotIn(List<Long> values) {
            addCriterion("user_ not in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserBetween(Long value1, Long value2) {
            addCriterion("user_ between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotBetween(Long value1, Long value2) {
            addCriterion("user_ not between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNull() {
            addCriterion("add_user is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNotNull() {
            addCriterion("add_user is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserEqualTo(Long value) {
            addCriterion("add_user =", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotEqualTo(Long value) {
            addCriterion("add_user <>", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThan(Long value) {
            addCriterion("add_user >", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("add_user >=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThan(Long value) {
            addCriterion("add_user <", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThanOrEqualTo(Long value) {
            addCriterion("add_user <=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserIn(List<Long> values) {
            addCriterion("add_user in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotIn(List<Long> values) {
            addCriterion("add_user not in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserBetween(Long value1, Long value2) {
            addCriterion("add_user between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotBetween(Long value1, Long value2) {
            addCriterion("add_user not between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockIsNull() {
            addCriterion("hr_alarm_lock is null");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockIsNotNull() {
            addCriterion("hr_alarm_lock is not null");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockEqualTo(Boolean value) {
            addCriterion("hr_alarm_lock =", value, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockNotEqualTo(Boolean value) {
            addCriterion("hr_alarm_lock <>", value, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockGreaterThan(Boolean value) {
            addCriterion("hr_alarm_lock >", value, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hr_alarm_lock >=", value, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockLessThan(Boolean value) {
            addCriterion("hr_alarm_lock <", value, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockLessThanOrEqualTo(Boolean value) {
            addCriterion("hr_alarm_lock <=", value, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockIn(List<Boolean> values) {
            addCriterion("hr_alarm_lock in", values, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockNotIn(List<Boolean> values) {
            addCriterion("hr_alarm_lock not in", values, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockBetween(Boolean value1, Boolean value2) {
            addCriterion("hr_alarm_lock between", value1, value2, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andHrAlarmLockNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hr_alarm_lock not between", value1, value2, "hrAlarmLock");
            return (Criteria) this;
        }

        public Criteria andSitLockIsNull() {
            addCriterion("sit_lock is null");
            return (Criteria) this;
        }

        public Criteria andSitLockIsNotNull() {
            addCriterion("sit_lock is not null");
            return (Criteria) this;
        }

        public Criteria andSitLockEqualTo(Boolean value) {
            addCriterion("sit_lock =", value, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockNotEqualTo(Boolean value) {
            addCriterion("sit_lock <>", value, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockGreaterThan(Boolean value) {
            addCriterion("sit_lock >", value, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sit_lock >=", value, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockLessThan(Boolean value) {
            addCriterion("sit_lock <", value, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockLessThanOrEqualTo(Boolean value) {
            addCriterion("sit_lock <=", value, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockIn(List<Boolean> values) {
            addCriterion("sit_lock in", values, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockNotIn(List<Boolean> values) {
            addCriterion("sit_lock not in", values, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockBetween(Boolean value1, Boolean value2) {
            addCriterion("sit_lock between", value1, value2, "sitLock");
            return (Criteria) this;
        }

        public Criteria andSitLockNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sit_lock not between", value1, value2, "sitLock");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andRadiusIsNull() {
            addCriterion("radius is null");
            return (Criteria) this;
        }

        public Criteria andRadiusIsNotNull() {
            addCriterion("radius is not null");
            return (Criteria) this;
        }

        public Criteria andRadiusEqualTo(Integer value) {
            addCriterion("radius =", value, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusNotEqualTo(Integer value) {
            addCriterion("radius <>", value, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusGreaterThan(Integer value) {
            addCriterion("radius >", value, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusGreaterThanOrEqualTo(Integer value) {
            addCriterion("radius >=", value, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusLessThan(Integer value) {
            addCriterion("radius <", value, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusLessThanOrEqualTo(Integer value) {
            addCriterion("radius <=", value, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusIn(List<Integer> values) {
            addCriterion("radius in", values, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusNotIn(List<Integer> values) {
            addCriterion("radius not in", values, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusBetween(Integer value1, Integer value2) {
            addCriterion("radius between", value1, value2, "radius");
            return (Criteria) this;
        }

        public Criteria andRadiusNotBetween(Integer value1, Integer value2) {
            addCriterion("radius not between", value1, value2, "radius");
            return (Criteria) this;
        }

        public Criteria andFenceIsNull() {
            addCriterion("fence is null");
            return (Criteria) this;
        }

        public Criteria andFenceIsNotNull() {
            addCriterion("fence is not null");
            return (Criteria) this;
        }

        public Criteria andFenceEqualTo(Boolean value) {
            addCriterion("fence =", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceNotEqualTo(Boolean value) {
            addCriterion("fence <>", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceGreaterThan(Boolean value) {
            addCriterion("fence >", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fence >=", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceLessThan(Boolean value) {
            addCriterion("fence <", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceLessThanOrEqualTo(Boolean value) {
            addCriterion("fence <=", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceIn(List<Boolean> values) {
            addCriterion("fence in", values, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceNotIn(List<Boolean> values) {
            addCriterion("fence not in", values, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceBetween(Boolean value1, Boolean value2) {
            addCriterion("fence between", value1, value2, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fence not between", value1, value2, "fence");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNull() {
            addCriterion("add_date is null");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNotNull() {
            addCriterion("add_date is not null");
            return (Criteria) this;
        }

        public Criteria andAddDateEqualTo(Date value) {
            addCriterion("add_date =", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotEqualTo(Date value) {
            addCriterion("add_date <>", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThan(Date value) {
            addCriterion("add_date >", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThanOrEqualTo(Date value) {
            addCriterion("add_date >=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThan(Date value) {
            addCriterion("add_date <", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThanOrEqualTo(Date value) {
            addCriterion("add_date <=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateIn(List<Date> values) {
            addCriterion("add_date in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotIn(List<Date> values) {
            addCriterion("add_date not in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateBetween(Date value1, Date value2) {
            addCriterion("add_date between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotBetween(Date value1, Date value2) {
            addCriterion("add_date not between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andSyncStatusIsNull() {
            addCriterion("sync_status is null");
            return (Criteria) this;
        }

        public Criteria andSyncStatusIsNotNull() {
            addCriterion("sync_status is not null");
            return (Criteria) this;
        }

        public Criteria andSyncStatusEqualTo(Byte value) {
            addCriterion("sync_status =", value, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusNotEqualTo(Byte value) {
            addCriterion("sync_status <>", value, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusGreaterThan(Byte value) {
            addCriterion("sync_status >", value, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("sync_status >=", value, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusLessThan(Byte value) {
            addCriterion("sync_status <", value, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusLessThanOrEqualTo(Byte value) {
            addCriterion("sync_status <=", value, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusIn(List<Byte> values) {
            addCriterion("sync_status in", values, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusNotIn(List<Byte> values) {
            addCriterion("sync_status not in", values, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusBetween(Byte value1, Byte value2) {
            addCriterion("sync_status between", value1, value2, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andSyncStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("sync_status not between", value1, value2, "syncStatus");
            return (Criteria) this;
        }

        public Criteria andHrSpanIsNull() {
            addCriterion("hr_span is null");
            return (Criteria) this;
        }

        public Criteria andHrSpanIsNotNull() {
            addCriterion("hr_span is not null");
            return (Criteria) this;
        }

        public Criteria andHrSpanEqualTo(Integer value) {
            addCriterion("hr_span =", value, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanNotEqualTo(Integer value) {
            addCriterion("hr_span <>", value, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanGreaterThan(Integer value) {
            addCriterion("hr_span >", value, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanGreaterThanOrEqualTo(Integer value) {
            addCriterion("hr_span >=", value, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanLessThan(Integer value) {
            addCriterion("hr_span <", value, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanLessThanOrEqualTo(Integer value) {
            addCriterion("hr_span <=", value, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanIn(List<Integer> values) {
            addCriterion("hr_span in", values, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanNotIn(List<Integer> values) {
            addCriterion("hr_span not in", values, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanBetween(Integer value1, Integer value2) {
            addCriterion("hr_span between", value1, value2, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andHrSpanNotBetween(Integer value1, Integer value2) {
            addCriterion("hr_span not between", value1, value2, "hrSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanIsNull() {
            addCriterion("position_span is null");
            return (Criteria) this;
        }

        public Criteria andPositionSpanIsNotNull() {
            addCriterion("position_span is not null");
            return (Criteria) this;
        }

        public Criteria andPositionSpanEqualTo(Integer value) {
            addCriterion("position_span =", value, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanNotEqualTo(Integer value) {
            addCriterion("position_span <>", value, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanGreaterThan(Integer value) {
            addCriterion("position_span >", value, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanGreaterThanOrEqualTo(Integer value) {
            addCriterion("position_span >=", value, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanLessThan(Integer value) {
            addCriterion("position_span <", value, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanLessThanOrEqualTo(Integer value) {
            addCriterion("position_span <=", value, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanIn(List<Integer> values) {
            addCriterion("position_span in", values, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanNotIn(List<Integer> values) {
            addCriterion("position_span not in", values, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanBetween(Integer value1, Integer value2) {
            addCriterion("position_span between", value1, value2, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andPositionSpanNotBetween(Integer value1, Integer value2) {
            addCriterion("position_span not between", value1, value2, "positionSpan");
            return (Criteria) this;
        }

        public Criteria andSleepStatusIsNull() {
            addCriterion("sleep_status is null");
            return (Criteria) this;
        }

        public Criteria andSleepStatusIsNotNull() {
            addCriterion("sleep_status is not null");
            return (Criteria) this;
        }

        public Criteria andSleepStatusEqualTo(Boolean value) {
            addCriterion("sleep_status =", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusNotEqualTo(Boolean value) {
            addCriterion("sleep_status <>", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusGreaterThan(Boolean value) {
            addCriterion("sleep_status >", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sleep_status >=", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusLessThan(Boolean value) {
            addCriterion("sleep_status <", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("sleep_status <=", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusIn(List<Boolean> values) {
            addCriterion("sleep_status in", values, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusNotIn(List<Boolean> values) {
            addCriterion("sleep_status not in", values, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("sleep_status between", value1, value2, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sleep_status not between", value1, value2, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeIsNull() {
            addCriterion("sleep_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeIsNotNull() {
            addCriterion("sleep_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeEqualTo(String value) {
            addCriterion("sleep_start_time =", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeNotEqualTo(String value) {
            addCriterion("sleep_start_time <>", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeGreaterThan(String value) {
            addCriterion("sleep_start_time >", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("sleep_start_time >=", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeLessThan(String value) {
            addCriterion("sleep_start_time <", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeLessThanOrEqualTo(String value) {
            addCriterion("sleep_start_time <=", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeLike(String value) {
            addCriterion("sleep_start_time like", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeNotLike(String value) {
            addCriterion("sleep_start_time not like", value, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeIn(List<String> values) {
            addCriterion("sleep_start_time in", values, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeNotIn(List<String> values) {
            addCriterion("sleep_start_time not in", values, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeBetween(String value1, String value2) {
            addCriterion("sleep_start_time between", value1, value2, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepStartTimeNotBetween(String value1, String value2) {
            addCriterion("sleep_start_time not between", value1, value2, "sleepStartTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeIsNull() {
            addCriterion("sleep_end_time is null");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeIsNotNull() {
            addCriterion("sleep_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeEqualTo(String value) {
            addCriterion("sleep_end_time =", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeNotEqualTo(String value) {
            addCriterion("sleep_end_time <>", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeGreaterThan(String value) {
            addCriterion("sleep_end_time >", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("sleep_end_time >=", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeLessThan(String value) {
            addCriterion("sleep_end_time <", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeLessThanOrEqualTo(String value) {
            addCriterion("sleep_end_time <=", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeLike(String value) {
            addCriterion("sleep_end_time like", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeNotLike(String value) {
            addCriterion("sleep_end_time not like", value, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeIn(List<String> values) {
            addCriterion("sleep_end_time in", values, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeNotIn(List<String> values) {
            addCriterion("sleep_end_time not in", values, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeBetween(String value1, String value2) {
            addCriterion("sleep_end_time between", value1, value2, "sleepEndTime");
            return (Criteria) this;
        }

        public Criteria andSleepEndTimeNotBetween(String value1, String value2) {
            addCriterion("sleep_end_time not between", value1, value2, "sleepEndTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_watch
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}