package cn.ac.sec.entity;

public class SysArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article_type.id_
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article_type.type_code
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article_type.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article_type
     *
     * @mbggenerated
     */
    public SysArticleType(Integer id, String typeCode, String typeName, Long createBy) {
        this.id = id;
        this.typeCode = typeCode;
        this.typeName = typeName;
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_article_type
     *
     * @mbggenerated
     */
    public SysArticleType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article_type.id_
     *
     * @return the value of sys_article_type.id_
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article_type.id_
     *
     * @param id the value for sys_article_type.id_
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article_type.type_code
     *
     * @return the value of sys_article_type.type_code
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article_type.type_code
     *
     * @param typeCode the value for sys_article_type.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article_type.type_name
     *
     * @return the value of sys_article_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article_type.type_name
     *
     * @param typeName the value for sys_article_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article_type.create_by
     *
     * @return the value of sys_article_type.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article_type.create_by
     *
     * @param createBy the value for sys_article_type.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }
}