package cn.ac.sec.dao;

import cn.ac.sec.entity.BizDevice;
import cn.ac.sec.entity.BizDeviceExample;
import java.util.List;
import java.util.Map;

import cn.ac.sec.entity.BizUser;
import org.apache.ibatis.annotations.*;
import org.ibase4j.model.ChartData;

public interface BizDeviceMapper {

    @Select({
            "select",
            "id_, device_code, device_type, add_user,add_time, user_, IMEI_",
            "from biz_device",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap ("BaseResultMap")
    BizDevice selectByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    int countByExample(BizDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    int deleteByExample(BizDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_device (id_, device_code, ",
        "device_type, add_user, ",
        "add_time, user_, ",
        "IMEI_)",
        "values (#{id,jdbcType=BIGINT}, #{deviceCode,jdbcType=INTEGER}, ",
        "#{deviceType,jdbcType=VARCHAR}, #{addUser,jdbcType=BIGINT}, ",
        "#{addTime,jdbcType=TIMESTAMP}, #{user,jdbcType=BIGINT}, ",
        "#{imei,jdbcType=BIGINT})"
    })
    int insert(BizDevice record);

    int updateByPrimaryKeySelective(BizDevice record);


    @Delete ({
            "delete from biz_device where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    int insertSelective(BizDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    List<BizDevice> selectByExample(BizDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizDevice record, @Param("example") BizDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizDevice record, @Param("example") BizDeviceExample example);

    int createNewDataTable(@Param ("table_name") String tableName);

    List<Map<String,Object>> deviceWithUserAndType(@Param ("keyword") String keyword);

    List<Map<String,Object>> deviceByUserId(@Param ("userId")Long userId);

    /*
       新增设备统计分析
     */
    List<ChartData> getRegisterCountByMonth(@Param("time") String time,@Param("typeCode")String typeCode);

    List<ChartData> getRegisterCountByWeek(@Param("time") String time,@Param("typeCode")String typeCode);

    List<ChartData> getRegisterCountByDay(@Param("year") String year,@Param("month") String month,@Param("typeCode")String typeCode);

   /*
        设备使用情况统计
    */

    List<ChartData> getUseWatch_bpCountByMonth(@Param("time") String time);

    List<ChartData> getUseWatch_bsCountByMonth(@Param("time") String time);

    List<ChartData> getUsePM10CountByMonth(@Param("time") String time);

    List<ChartData> getUseSpO208CountByMonth(@Param("time") String time);

    List<ChartData> getUseBG01CountByMonth(@Param("time") String time);

    List<ChartData> getUseBC01CountByMonth(@Param("time") String time);

    List<ChartData> getUseNIBP04CountByMonth(@Param("time") String time);

    List<ChartData> getUseSWANCountByMonth(@Param("time") String time);

    List<ChartData> getUseWatch_hrCountByMonth(@Param("time") String time);

    List<ChartData> getUseLay_downCountByMonth(@Param("time") String time);



    List<ChartData> getUseWatch_bpCountByWeek(@Param("time") String time);

    List<ChartData> getUseWatch_bsCountByWeek(@Param("time") String time);

    List<ChartData> getUsePM10CountByWeek(@Param("time") String time);

    List<ChartData> getUseSpO208CountByWeek(@Param("time") String time);

    List<ChartData> getUseBG01CountByWeek(@Param("time") String time);

    List<ChartData> getUseBC01CountByWeek(@Param("time") String time);

    List<ChartData> getUseNIBP04CountByWeek(@Param("time") String time);

    List<ChartData> getUseSWANCountByWeek(@Param("time") String time);

    List<ChartData> getUseWatch_hrCountByWeek(@Param("time") String time);

    List<ChartData> getUseLay_downCountByWeek(@Param("time") String time);



    List<ChartData> getUseWatch_bpCountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseWatch_bsCountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUsePM10CountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseSpO208CountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseBG01CountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseBC01CountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseNIBP04CountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseSWANCountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseWatch_hrCountByDay(@Param("year") String year,@Param("month") String month);

    List<ChartData> getUseLay_downCountByDay(@Param("year") String year,@Param("month") String month);

    /**
     * 按月查询设备总使用量
     *
     */
    int getAllWatch_bpDataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllWatch_bsDataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllPM10DataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllSpO208DataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllBG01DataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllBC01DataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllNIBP04DataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllSWANDataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllWatch_hrDataByMonth(@Param("year") String year, @Param("month")int month);

    int getAllLay_downDataByMonth(@Param("year") String year, @Param("month")int month);

    /**
     * 按周查询设备总使用量
     *
     */
    int getAllWatch_bpDataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllWatch_bsDataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllPM10DataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllSpO208DataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllBG01DataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllBC01DataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllNIBP04DataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllSWANDataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllWatch_hrDataByWeek(@Param("year") String year, @Param("week")int week);

    int getAllLay_downDataByWeek(@Param("year") String year, @Param("week")int week);



    /**
     * 按日查询设备总使用量
     *
     */
    int getAllWatch_bpDataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllWatch_bsDataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllPM10DataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllSpO208DataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllBG01DataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllBC01DataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllNIBP04DataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllSWANDataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllWatch_hrDataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);

    int getAllLay_downDataByDay(@Param("year") int year, @Param("month")int month,@Param("day")int day);
}