package cn.ac.sec.dao;

import cn.ac.sec.entity.BizDeviceType;
import cn.ac.sec.entity.BizDeviceTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizDeviceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    int countByExample(BizDeviceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    int deleteByExample(BizDeviceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_device_type",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_device_type (id_, name_, ",
        "type_code, icon_)",
        "values (#{id,jdbcType=TINYINT}, #{name,jdbcType=VARCHAR}, ",
        "#{typeCode,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR})"
    })
    int insert(BizDeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    int insertSelective(BizDeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    List<BizDeviceType> selectByExample(BizDeviceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, name_, type_code, icon_",
        "from biz_device_type",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    @ResultMap("BaseResultMap")
    BizDeviceType selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizDeviceType record, @Param("example") BizDeviceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizDeviceType record, @Param("example") BizDeviceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizDeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_type
     *
     * @mbggenerated
     */
    @Update({
        "update biz_device_type",
        "set name_ = #{name,jdbcType=VARCHAR},",
          "type_code = #{typeCode,jdbcType=VARCHAR},",
          "icon_ = #{icon,jdbcType=VARCHAR}",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    int updateByPrimaryKey(BizDeviceType record);
}