package cn.ac.sec.dao;

import cn.ac.sec.entity.BizDeviceData;
import cn.ac.sec.entity.BizDeviceDataExample;
import cn.ac.sec.entity.BizDeviceDataKey;
import org.apache.ibatis.annotations.*;

import java.util.Date;
import java.util.List;

public interface BizDeviceDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    int countByExample(BizDeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    int deleteByExample(BizDeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ${tableName}",
        "where device_code = #{deviceCode,jdbcType=INTEGER}",
          "and datetime_measure = #{datetimeMeasure,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(BizDeviceDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ${tableName} (datetime_measure, ",
        "datetime_update, user_id, ",
        "data_)",
        "values (#{datetimeMeasure,jdbcType=TIMESTAMP}, ",
        "#{datetimeUpdate,jdbcType=TIMESTAMP}, #{userId,jdbcType=BIGINT}, ",
        "#{data,jdbcType=VARCHAR})"
    })
    int insert(BizDeviceData record);

    @Select ({
            " select data_ from ${tableName} where user_id = #{userId,jdbcType=BIGINT} order by datetime_measure desc limit 1 "
    })
    @ResultType(java.lang.String.class)
    String selectLatestByUser(@Param ("userId") Long id, @Param ("tableName") String tableName);

    @Select ({
            "select data_ from ${tableName} where id_= #{id,jdbcType=BIGINT}"
    })
    @ResultType (java.lang.String.class)
    String selectById(@Param ("id") Long id, @Param ("tableName") String tableName);

    @Select({
            "select data_ from ${tableName} where datetime_measure = #{time,jdbcType=TIMESTAMP} and user_id=#{userId,jdbcType=BIGINT} limit 1"
    })
    @ResultType(java.lang.String.class)
    String selectByTime(@Param("userId") Long userId, @Param("time") Date time, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    int insertSelective(BizDeviceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    List<BizDeviceData> selectByExample(BizDeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    @Select({
        "select",
            "data_",
        "from ${tableName}",
            "where id=${id} "
    })
    @ResultType(java.lang.String.class)
    String selectByPrimaryKey(Long id, String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizDeviceData record, @Param("example") BizDeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizDeviceData record, @Param("example") BizDeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizDeviceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ${tableName}
     *
     * @mbggenerated
     */
    @Update({
        "update ${tableName}",
        "set datetime_update = #{datetimeUpdate,jdbcType=TIMESTAMP},",
          "data_ = #{data,jdbcType=VARCHAR}",
        "where userId = #{userId,jdbcType=INTEGER}",
          "and datetime_measure = #{datetimeMeasure,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(BizDeviceData record);


    List<BizDeviceData> selectByExampleWithoutData(BizDeviceDataExample example);
}