package cn.ac.sec.dao;

import cn.ac.sec.entity.BizLogWatch;
import cn.ac.sec.entity.BizLogWatchExample;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface BizLogWatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    int countByExample(BizLogWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    int deleteByExample(BizLogWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_log_watch",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    @Insert({
            "insert into biz_log_watch (id_, user_operate, ",
            "user_id, operate_date, ",
            "operation)",
            "values (#{id,jdbcType=BIGINT}, #{userOperate,jdbcType=BIGINT}, ",
            "#{userId,jdbcType=BIGINT}, #{operateDate,jdbcType=TIMESTAMP}, ",
            "#{operation,jdbcType=VARCHAR})"
    })
    int insert(BizLogWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    int insertSelective(BizLogWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    List<BizLogWatch> selectByExample(BizLogWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    @Select({
        "select",
            "id_, user_operate, user_id, operate_date, operation",
        "from biz_log_watch",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizLogWatch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizLogWatch record, @Param("example") BizLogWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizLogWatch record, @Param("example") BizLogWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizLogWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_log_watch
     *
     * @mbggenerated
     */
    @Update({
        "update biz_log_watch",
            "set user_operate = #{userOperate,jdbcType=BIGINT},",
            "user_id = #{userId,jdbcType=BIGINT},",
            "operate_date = #{operateDate,jdbcType=TIMESTAMP},",
          "operation = #{operation,jdbcType=VARCHAR}",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizLogWatch record);

    List<Map<String, Object>> getOperationsByUser(@Param("userId") Long userId);

}