package cn.ac.sec.dao;

import cn.ac.sec.entity.BizMessageStep;
import cn.ac.sec.entity.BizMessageStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizMessageStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    int countByExample(BizMessageStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    int deleteByExample(BizMessageStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_message_step",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_message_step (id_, user_, ",
        "time_, count_, upload_date)",
        "values (#{id,jdbcType=BIGINT}, #{user,jdbcType=BIGINT}, ",
        "#{time,jdbcType=TIMESTAMP}, #{count,jdbcType=INTEGER}, #{uploadDate,jdbcType=DATE})"
    })
    int insert(BizMessageStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    int insertSelective(BizMessageStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    List<BizMessageStep> selectByExample(BizMessageStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, user_, time_, count_, upload_date",
        "from biz_message_step",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizMessageStep selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizMessageStep record, @Param("example") BizMessageStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizMessageStep record, @Param("example") BizMessageStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizMessageStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_step
     *
     * @mbggenerated
     */
    @Update({
        "update biz_message_step",
        "set user_ = #{user,jdbcType=BIGINT},",
          "time_ = #{time,jdbcType=TIMESTAMP},",
          "count_ = #{count,jdbcType=INTEGER},",
          "upload_date = #{uploadDate,jdbcType=DATE}",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizMessageStep record);
}