package cn.ac.sec.dao;

import cn.ac.sec.entity.BizMessageAlarmType;
import cn.ac.sec.entity.BizMessageAlarmTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizMessageAlarmTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int countByExample(BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int deleteByExample(BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_message_alarm_type",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_message_alarm_type (id_, name_, ",
        "icon_, level_, order_, ",
        "code_, device_type, ",
        "description_)",
        "values (#{id,jdbcType=TINYINT}, #{name,jdbcType=VARCHAR}, ",
        "#{icon,jdbcType=VARCHAR}, #{level,jdbcType=TINYINT}, #{order,jdbcType=TINYINT}, ",
        "#{code,jdbcType=VARCHAR}, #{deviceType,jdbcType=TINYINT}, ",
        "#{description,jdbcType=LONGVARCHAR})"
    })
    int insert(BizMessageAlarmType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int insertSelective(BizMessageAlarmType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    List<BizMessageAlarmType> selectByExampleWithBLOBs(BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    List<BizMessageAlarmType> selectByExample(BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, name_, icon_, level_, order_, code_, device_type, description_",
        "from biz_message_alarm_type",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    BizMessageAlarmType selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizMessageAlarmType record, @Param("example") BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BizMessageAlarmType record, @Param("example") BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizMessageAlarmType record, @Param("example") BizMessageAlarmTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizMessageAlarmType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    @Update({
        "update biz_message_alarm_type",
        "set name_ = #{name,jdbcType=VARCHAR},",
          "icon_ = #{icon,jdbcType=VARCHAR},",
          "level_ = #{level,jdbcType=TINYINT},",
          "order_ = #{order,jdbcType=TINYINT},",
          "code_ = #{code,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=TINYINT},",
          "description_ = #{description,jdbcType=LONGVARCHAR}",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    int updateByPrimaryKeyWithBLOBs(BizMessageAlarmType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_alarm_type
     *
     * @mbggenerated
     */
    @Update({
        "update biz_message_alarm_type",
        "set name_ = #{name,jdbcType=VARCHAR},",
          "icon_ = #{icon,jdbcType=VARCHAR},",
          "level_ = #{level,jdbcType=TINYINT},",
          "order_ = #{order,jdbcType=TINYINT},",
          "code_ = #{code,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=TINYINT}",
        "where id_ = #{id,jdbcType=TINYINT}"
    })
    int updateByPrimaryKey(BizMessageAlarmType record);
}