package cn.ac.sec.dao;

import cn.ac.sec.entity.BizMessagePosition;
import cn.ac.sec.entity.BizMessagePositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizMessagePositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    int countByExample(BizMessagePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    int deleteByExample(BizMessagePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_message_position",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_message_position (id_, user_, ",
        "time_, timestamp_, ",
        "longitude_, latitude_)",
        "values (#{id,jdbcType=BIGINT}, #{user,jdbcType=BIGINT}, ",
        "#{time,jdbcType=TIMESTAMP}, #{timestamp,jdbcType=INTEGER}, ",
        "#{longitude,jdbcType=DOUBLE}, #{latitude,jdbcType=DOUBLE})"
    })
    int insert(BizMessagePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    int insertSelective(BizMessagePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    List<BizMessagePosition> selectByExample(BizMessagePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, user_, time_, timestamp_, longitude_, latitude_",
        "from biz_message_position",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizMessagePosition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizMessagePosition record, @Param("example") BizMessagePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizMessagePosition record, @Param("example") BizMessagePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizMessagePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_message_position
     *
     * @mbggenerated
     */
    @Update({
        "update biz_message_position",
        "set user_ = #{user,jdbcType=BIGINT},",
          "time_ = #{time,jdbcType=TIMESTAMP},",
          "timestamp_ = #{timestamp,jdbcType=INTEGER},",
          "longitude_ = #{longitude,jdbcType=DOUBLE},",
          "latitude_ = #{latitude,jdbcType=DOUBLE}",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizMessagePosition record);
}