package cn.ac.sec.dao;

import cn.ac.sec.entity.BizPhoneCall;
import cn.ac.sec.entity.BizPhoneCallExample;
import cn.ac.sec.entity.BizPhoneCallWithBLOBs;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface BizPhoneCallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int countByExample(BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int deleteByExample(BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    @Delete({
            "delete from biz_phone_call",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    @Insert({
            "insert into biz_phone_call (id_, consumer_, ",
            "operator_, call_time, ",
            "save_time, detail_, ",
            "treament_)",
            "values (#{id,jdbcType=BIGINT}, #{consumer,jdbcType=BIGINT}, ",
            "#{operator,jdbcType=BIGINT}, #{callTime,jdbcType=TIMESTAMP}, ",
            "#{saveTime,jdbcType=TIMESTAMP}, #{detail,jdbcType=LONGVARCHAR}, ",
            "#{treament,jdbcType=LONGVARCHAR})"
    })
    int insert(BizPhoneCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int insertSelective(BizPhoneCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    List<BizPhoneCallWithBLOBs> selectByExampleWithBLOBs(BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    List<BizPhoneCall> selectByExample(BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id_, consumer_, operator_, call_time, save_time, detail_, treament_",
            "from biz_phone_call",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("ResultMapWithBLOBs")
    BizPhoneCallWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizPhoneCallWithBLOBs record, @Param("example") BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BizPhoneCallWithBLOBs record, @Param("example") BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizPhoneCall record, @Param("example") BizPhoneCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizPhoneCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    @Update({
            "update biz_phone_call",
            "set consumer_ = #{consumer,jdbcType=BIGINT},",
            "operator_ = #{operator,jdbcType=BIGINT},",
            "call_time = #{callTime,jdbcType=TIMESTAMP},",
            "save_time = #{saveTime,jdbcType=TIMESTAMP},",
            "detail_ = #{detail,jdbcType=LONGVARCHAR},",
            "treament_ = #{treament,jdbcType=LONGVARCHAR}",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(BizPhoneCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_phone_call
     *
     * @mbggenerated
     */
    @Update({
            "update biz_phone_call",
            "set consumer_ = #{consumer,jdbcType=BIGINT},",
            "operator_ = #{operator,jdbcType=BIGINT},",
            "call_time = #{callTime,jdbcType=TIMESTAMP},",
            "save_time = #{saveTime,jdbcType=TIMESTAMP}",
            "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizPhoneCall record);

    List<Map<String, Object>> getCallList(@Param("keyword") String keyword);

}