package cn.ac.sec.dao;

import cn.ac.sec.entity.BizRelationUser;
import cn.ac.sec.entity.BizRelationUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizRelationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    int countByExample(BizRelationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    int deleteByExample(BizRelationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_relation_user",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_relation_user (id_, parent_, ",
        "child_, add_date, ",
        "unbind_status, unbind_date)",
        "values (#{id,jdbcType=BIGINT}, #{parent,jdbcType=BIGINT}, ",
        "#{child,jdbcType=BIGINT}, #{addDate,jdbcType=TIMESTAMP}, ",
        "#{unbindStatus,jdbcType=TINYINT}, #{unbindDate,jdbcType=TIMESTAMP})"
    })
    int insert(BizRelationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    int insertSelective(BizRelationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    List<BizRelationUser> selectByExample(BizRelationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, parent_, child_, add_date, unbind_status, unbind_date",
        "from biz_relation_user",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizRelationUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizRelationUser record, @Param("example") BizRelationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizRelationUser record, @Param("example") BizRelationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRelationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_relation_user
     *
     * @mbggenerated
     */
    @Update({
        "update biz_relation_user",
        "set parent_ = #{parent,jdbcType=BIGINT},",
          "child_ = #{child,jdbcType=BIGINT},",
          "add_date = #{addDate,jdbcType=TIMESTAMP},",
          "unbind_status = #{unbindStatus,jdbcType=TINYINT},",
          "unbind_date = #{unbindDate,jdbcType=TIMESTAMP}",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizRelationUser record);
}