package cn.ac.sec.dao;

import cn.ac.sec.entity.BizUserTag;
import cn.ac.sec.entity.BizUserTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizUserTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int countByExample(BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int deleteByExample(BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_user_tag",
        "where id_ = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_user_tag (id_, tag_name, ",
        "tag_detail)",
        "values (#{id,jdbcType=INTEGER}, #{tagName,jdbcType=VARCHAR}, ",
        "#{tagDetail,jdbcType=LONGVARCHAR})"
    })
    int insert(BizUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int insertSelective(BizUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    List<BizUserTag> selectByExampleWithBLOBs(BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    List<BizUserTag> selectByExample(BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, tag_name, tag_detail",
        "from biz_user_tag",
        "where id_ = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    BizUserTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizUserTag record, @Param("example") BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BizUserTag record, @Param("example") BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizUserTag record, @Param("example") BizUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    @Update({
        "update biz_user_tag",
        "set tag_name = #{tagName,jdbcType=VARCHAR},",
          "tag_detail = #{tagDetail,jdbcType=LONGVARCHAR}",
        "where id_ = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(BizUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_tag
     *
     * @mbggenerated
     */
    @Update({
        "update biz_user_tag",
        "set tag_name = #{tagName,jdbcType=VARCHAR}",
        "where id_ = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BizUserTag record);

    List<BizUserTag> getTagsByUserId(@Param ("userId") Long userId);

    List<BizUserTag> selectListWithDetail();

    List<BizUserTag> getTagWithoutUser(@Param ("userId") Long userId);
}