package cn.ac.sec.dao;

import cn.ac.sec.entity.BizWatch;
import cn.ac.sec.entity.BizWatchExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BizWatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    int countByExample(BizWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    int deleteByExample(BizWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_watch",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_watch (id_, IMEI_, ",
        "last_online_time, watch_phone_num, ",
        "user_, add_user, hr_alarm_lock, ",
        "sit_lock, longitude, latitude, ",
        "radius, fence, add_date, ",
        "sync_status, hr_span, ",
        "position_span, sleep_status, ",
        "sleep_start_time, sleep_end_time)",
        "values (#{id,jdbcType=BIGINT}, #{imei,jdbcType=BIGINT}, ",
        "#{lastOnlineTime,jdbcType=TIMESTAMP}, #{watchPhoneNum,jdbcType=VARCHAR}, ",
        "#{user,jdbcType=BIGINT}, #{addUser,jdbcType=BIGINT}, #{hrAlarmLock,jdbcType=BIT}, ",
        "#{sitLock,jdbcType=BIT}, #{longitude,jdbcType=DOUBLE}, #{latitude,jdbcType=DOUBLE}, ",
        "#{radius,jdbcType=INTEGER}, #{fence,jdbcType=BIT}, #{addDate,jdbcType=TIMESTAMP}, ",
        "#{syncStatus,jdbcType=TINYINT}, #{hrSpan,jdbcType=INTEGER}, ",
        "#{positionSpan,jdbcType=INTEGER}, #{sleepStatus,jdbcType=BIT}, ",
        "#{sleepStartTime,jdbcType=VARCHAR}, #{sleepEndTime,jdbcType=VARCHAR})"
    })
    int insert(BizWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    int insertSelective(BizWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    List<BizWatch> selectByExample(BizWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_, IMEI_, last_online_time, watch_phone_num, user_, add_user, hr_alarm_lock, ",
        "sit_lock, longitude, latitude, radius, fence, add_date, sync_status, hr_span, ",
        "position_span, sleep_status, sleep_start_time, sleep_end_time",
        "from biz_watch",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizWatch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizWatch record, @Param("example") BizWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizWatch record, @Param("example") BizWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_watch
     *
     * @mbggenerated
     */
    @Update({
        "update biz_watch",
        "set IMEI_ = #{imei,jdbcType=BIGINT},",
          "last_online_time = #{lastOnlineTime,jdbcType=TIMESTAMP},",
          "watch_phone_num = #{watchPhoneNum,jdbcType=VARCHAR},",
          "user_ = #{user,jdbcType=BIGINT},",
          "add_user = #{addUser,jdbcType=BIGINT},",
          "hr_alarm_lock = #{hrAlarmLock,jdbcType=BIT},",
          "sit_lock = #{sitLock,jdbcType=BIT},",
          "longitude = #{longitude,jdbcType=DOUBLE},",
          "latitude = #{latitude,jdbcType=DOUBLE},",
          "radius = #{radius,jdbcType=INTEGER},",
          "fence = #{fence,jdbcType=BIT},",
          "add_date = #{addDate,jdbcType=TIMESTAMP},",
          "sync_status = #{syncStatus,jdbcType=TINYINT},",
          "hr_span = #{hrSpan,jdbcType=INTEGER},",
          "position_span = #{positionSpan,jdbcType=INTEGER},",
          "sleep_status = #{sleepStatus,jdbcType=BIT},",
          "sleep_start_time = #{sleepStartTime,jdbcType=VARCHAR},",
          "sleep_end_time = #{sleepEndTime,jdbcType=VARCHAR}",
        "where id_ = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizWatch record);

    List<Map<String,Object>> watchWithUser(@Param ("keyword") String keyword);

}